# Generated by Django 6.0.3 on 2026-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("Codigo", models.AutoField(primary_key=True, serialize=False)),
                ("Nombre", models.TextField(max_length=25)),
                ("Cantidad", models.IntegerField()),
                ("Precio", models.FloatField()),
            ],
        ),
    ]
