# Generated by Django 4.2.11 on 2026-03-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_producto_descripcion_categoria_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
